### PR TITLE
How to hire a developer

### PR DESCRIPTION
**Pull request by ssung1bu**

### CODE REVIEW

**Comment by ssung1bu** [comment]
@jabonite33 @ichen15 please review my branch and provide any feedback. thanks! :smile:

**Comment by jabonite33** [comment]
Looks great @ssung1bu! :+1: Liked the infographic - the pointer about finding out their personal pay range ahead of time was helpful; I thought from class that all the good programmers were paid the same ($125/hr) so good to be aware that there may be some some variation.

**Comment by ssung1bu** [comment]
great! thanks @jabonite33! looks like i got the :+1: from you to ship. @ichen15 do i have the :+1: from you?

**Comment by ichen15** [comment]
Hi @ssung1bu! I really enjoyed the flowchart on the process to hire a good developer.  Also, I found in The Pragmatic Programmer that a good developer should also not "live with broken windows".  This means that programmers and developers should not leave bad designs, wrong decisions, or poor code unrepaired.  A good developer should fix something wrong as soon as it is discovered. Just thought that I would bring that up in case you want to add to your takeaway.  

Otherwise, everything looks great! :+1:

**Pull request merged**
